/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.93.0
  Forc version: 0.62.0
  Fuel-Core version: 0.31.0
*/

export type { ContractContractAbi } from './ContractContractAbi';
export type { RegistryContractAbi } from './RegistryContractAbi';

export { ContractContractAbi__factory } from './factories/ContractContractAbi__factory';
export { RegistryContractAbi__factory } from './factories/RegistryContractAbi__factory';
